import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { GlobalModal } from "@/components/use-dialog";
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen` } 
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            
            enableSystem
            disableTransitionOnChange
          >

          <Navbar/>
          <div className="container max-w-5xl mx-auto">
            
        {children}
          </div>
          <Toaster richColors/>
          <GlobalModal/>
          </ThemeProvider>
          
      </body>
    </html>
  );
}
